services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - .env
    mem_limit: 1g
    extra_hosts:
      - "host.docker.internal:host-gateway"
